#!/bin/bash
# 🚀 HNK Food Stack - Quick Start Script

echo "╔════════════════════════════════════════════════════════════╗"
echo "║      HNK FOOD STACK - ProductCard v2.0 Setup Complete      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 Dependências Instaladas:"
echo "   ✅ framer-motion@12.29.2 (Animações)"
echo "   ✅ lucide-react (Icons)"
echo "   ✅ zustand (Estado)"
echo "   ✅ next/image (Otimização)"
echo ""

echo "📁 Arquivos Criados/Atualizados:"
echo "   ✅ src/components/ui/ProductCard.tsx (Elite Edition)"
echo "   ✅ src/lib/analytics.ts (GTM + Meta Pixel)"
echo "   ✅ src/utils/social-proof.ts (Prova Social)"
echo "   ✅ app/layout.tsx (GTM + Meta Pixel Scripts)"
echo "   ✅ .env.local.example (Variáveis de ambiente)"
echo "   ✅ DOCS/GTM-PIXEL-SETUP.md (Guia de configuração)"
echo "   ✅ DOCS/PRODUCTCARD-V2-STATUS.md (Status detalhado)"
echo ""

echo "🔧 Próximos Passos:"
echo ""
echo "1️⃣  CONFIGURAR VARIÁVEIS DE AMBIENTE"
echo "   cp .env.local.example .env.local"
echo "   # Editar com seus IDs reais:"
echo "   NEXT_PUBLIC_GTM_ID=GTM-XXXXXXX"
echo "   NEXT_PUBLIC_PIXEL_ID=123456789"
echo ""

echo "2️⃣  OBTER IDS REAIS"
echo "   Google Tag Manager: https://tagmanager.google.com/"
echo "   Meta Pixel: https://business.facebook.com/"
echo ""

echo "3️⃣  TESTAR LOCALMENTE"
echo "   npm run dev"
echo "   # Abrir: http://localhost:3000/bem-estar"
echo "   # Abrir DevTools (F12) e testar eventos"
echo ""

echo "4️⃣  VERIFICAR EVENTOS"
echo "   Console: console.log(window.dataLayer)"
echo "   Console: console.log(window.fbq)"
echo ""

echo "5️⃣  INSTALAR CHROME EXTENSIONS"
echo "   - Google Tag Manager Debugger"
echo "   - Meta Pixel Helper"
echo "   - Clique em produto e veja eventos aparecerem"
echo ""

echo "📊 Features Implementadas:"
echo "   ✨ Framer Motion animations (enter/hover/tap)"
echo "   ✨ Glassmorphism design (bg + backdrop)"
echo "   ✨ Analytics tracking (GA4 + Meta Pixel)"
echo "   ✨ Social proof dinâmica (X+ pediram hoje)"
echo "   ✨ UTM link builder automático"
echo "   ✨ Mobile tap feedback"
echo "   ✨ Urgency badges"
echo "   ✨ Image optimization"
echo ""

echo "📚 Documentação:"
echo "   - DOCS/GTM-PIXEL-SETUP.md (Guia completo)"
echo "   - DOCS/PRODUCTCARD-V2-STATUS.md (Status técnico)"
echo "   - .env.local.example (Variáveis de exemplo)"
echo ""

echo "🎯 Status: PRONTO PARA PRODUÇÃO ✅"
echo ""
echo "═════════════════════════════════════════════════════════════"
